---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases: vagrant

  # The drush make file to use
  makefile: conf/site.make

  # Define project Drupal version
  drupal_version: d7

  # Directory used to build the site
  temporary: _build

  make_cache: .make_cache

  # The final produced Drupal installation
  final: current

  # Directory which will house all the previous builds
  previous: builds

  # Installation profile to use
  profile: wk

  # Site name given at installation phase
  site: Wundersite
  
  # If the site is a multisite system where drupal is bootstrapped from a different directory than
  # current/sites/default, you can define the folder here. Also note the symlink/copying of sites.php
  #multisite_site: myspecialsite
 
  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: sites/default/files
    - code/modules: sites/all/modules/custom
    - code/themes: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/local.settings.php: sites/default/settings.php
    # Only for multisite projects
    #- conf/sites.php: sites/sites.php
    - conf/_ping.php: _ping.php

# Test environment:
test:

  aliases: stage

  # Test environment only symlinks files
  link:
    - files: sites/default/files

  # Other files are copied, again note the settings.php, in our test enviroment we want to use another settings file.
  copy:
    - code/modules: sites/all/modules/custom
    - code/themes: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/test.settings.php: sites/default/settings.php
    - conf/_ping.php: _ping.php

  # We can provide local commands or override global ones.
  local_commands:

    # Running command ./build.sh hello test will print Hello world!
    hello:
      - shell: echo "Hello world!"

# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - files: sites/default/files

  # Other files are copied, note settings.php
  copy:
    - code/modules: sites/all/modules/custom
    - code/themes: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/prod.settings.php: sites/default/settings.php
    - conf/_ping.php: _ping.php
